name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  path: ^1.9.1
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  
flutter:
  uses-material-design: true
